events {
    # Define cuántas conexiones simultáneas puede manejar cada worker de NGINX
    worker_connections 1024;
}

http {
    # Configuraciones básicas para mejorar el rendimiento
    sendfile on;
    tcp_nopush on;
    tcp_nodelay on;
    keepalive_timeout 65;

    server {
        # El Gateway escuchará en el puerto 80 (el puerto web estándar por defecto)
        listen 80;

        # =========================================================
        # 1. ENRUTAMIENTO HACIA EL MICROSERVICIO A (Java - Inventario)
        # =========================================================
        location /api/transaccion {
            # Usamos el nombre del contenedor de Docker como si fuera una URL
            proxy_pass http://inventory-service:5001;
            
            # Pasamos los encabezados originales para que tu log de Java siga mostrando la IP real
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        }

        location /api/inventario {
            proxy_pass http://inventory-service:5001;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        }

        # =========================================================
        # 2. ENRUTAMIENTO HACIA EL MICROSERVICIO B (Python - Facturación)
        # =========================================================
        location /api/facturacion {
            # Asumiremos que levantaremos FastAPI en el puerto 8000
            proxy_pass http://billing-service:8000;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        }

        # =========================================================
        # 3. ENRUTAMIENTO HACIA EL FRONTEND (React/Vite)
        # =========================================================
        location / {
            # Vite usa el puerto 5173 por defecto en desarrollo
            proxy_pass http://frontend:5173;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            
            # Soporte para WebSockets (Necesario para el hot-reload de Vite)
            proxy_set_header Upgrade $http_upgrade;
            proxy_set_header Connection "upgrade";
        }
    }
}